name       : kbookmarks
version    : 5.100.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kbookmarks-5.100.0.tar.xz : 236cf8eef90b1a9737948d10e3c9aae1b6ca35ff7d5b2621b3a2aa61675e84ae
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
