name       : kbookmarks
version    : 5.64.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kbookmarks-5.64.0.tar.xz : 51343a57b50032d60ffae123f426cdd67cd290ce306ae494c1956d0b899d4ff2
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kcoreaddons-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
