name       : kbookmarks
version    : 5.69.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kbookmarks-5.69.0.tar.xz : 9bd8c3226cde3fa307cc72875fe3f2b768949c16ef3b198e01a49a39b1624ea4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kcoreaddons-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
