name       : kbookmarks
version    : 5.71.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kbookmarks-5.71.0.tar.xz : e00db1e62a769863a1bf90bb508f108f2740298aa40173cad34ef34a1c23a01a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kcoreaddons-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
