name       : kbookmarks
version    : 5.106.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kbookmarks-5.106.0.tar.xz : 8d3115d42a6ad460d6e37eeac714bd55ecf15616be224144e243f552a9f33628
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
