name       : kbookmarks
version    : 5.60.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kbookmarks-5.60.0.tar.xz : a2b77f0b084211badce2eb90c19e00caf078ab59512c326ed1c90f4a58de0d9f
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kcoreaddons-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
