name       : kbookmarks
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/kbookmarks-5.35.0.tar.xz : ef94ceb2a8450c85e3c28a35c6828daea2e6d1849ef57f30943812d993c28e18
license    : LGPL-2.1
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
