name       : kbookmarks
version    : 5.81.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kbookmarks-5.81.0.tar.xz : f5bfcc85d58b35439252f6e3d086a4deb359c4a0649fdfa57a96960cf7a00f2f
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
