name       : kbookmarks
version    : 5.85.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kbookmarks-5.85.0.tar.xz : 36130d9347beee614574ee7f6030279d1c425bbcdca759826a174026eb532a4b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
