name       : kbookmarks
version    : 5.43.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kbookmarks-5.43.0.tar.xz : 05b36907e7a833809cc15a4650a52914e177ad2db5a8ccd7eda68a61a172f944
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
