name       : kbookmarks
version    : 5.45.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kbookmarks-5.45.0.tar.xz : ad8a11ce7079674a9fbdb22c0e26116f5e6c1b4047587f3d06f759ba497c2046
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
