name       : kbookmarks
version    : 5.66.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kbookmarks-5.66.0.tar.xz : b225463ec0fe2424a1f5e70c83b02e3ece6a3ca80832cd2621732d18d7160a43
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kcoreaddons-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
