name       : kbookmarks
version    : 5.101.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/kbookmarks-5.101.0.tar.xz : 5d91617a36985af7b589fd6a43406067061667026578fdf3d20ac7b0f239702a
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
