name       : kbookmarks
version    : 5.87.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/kbookmarks-5.87.0.tar.xz : dd268cb6d437cf74e46468561db465b32dac4e9c93a17113e83be1a62fd09c4e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
