name       : kbookmarks
version    : 5.44.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kbookmarks-5.44.0.tar.xz : 19c66764c59709ebe34fcfef334d7a98a2c3c6fa8d69066a3cd28e38747a9c13
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
